flavors: 
  - test
  - accept
  - production
  - release

actions:
  pre:
    - echo "This is a pre-build command for flavor: {flavor}"

ios:
  files:
    "ios/Runner/GoogleService-Info.plist":
      release: "firebase/GoogleService-Info-release.plist"
      production: "firebase/GoogleService-Info-production.plist"
      accept: "firebase/GoogleService-Info-accept.plist"
      test: "firebase/GoogleService-Info-test.plist"

android:
  files:
    "android/app/google-services.json": 
      *: "firebase/google-services.json"