flavors: 
  - test
  - accept
  - production
  - release

ios:
  files:
    "ios/Runner/GoogleService-Info.plist":
      release: "firebase/GoogleService-Info-release.plist"
      production: "firebase/GoogleService-Info-production.plist"
      accept: "firebase/GoogleService-Info-accept.plist"
      test: "firebase/GoogleService-Info-test.plist"

android:
  files:
    "android/app/google-services.json": 
      test,accept,production,release: "firebase/google-services.json"