require 'flttr/version.rb'
require 'commands/buildable.rb'
require 'commands/run.rb'
require 'commands/build.rb'
require 'commands/upgrade.rb'
require 'commands/config.rb'
require 'settings.rb'
require 'updater.rb'