import_from_git(url: 'git@gitlab.e-sites.nl:team-i/ios/fastlane.git')

default_platform :ios

platform :ios do

    override_lane :pre_setup do |options|
        sh "bundle exec pod repo update trunk"
        UI.message "pre_setup override -> Environment #{options[:environment]}".yellow
        
        sh "flutter clean"
        if options[:lane] == "resign_ipa"
            sh "flutter pub get"
        else
            flavor = "release"
            if options[:environment] != "release"
                flavor = options[:environment]
            end

            sh "flutter build ios --release --no-codesign --flavor #{options[:environment]} --target #{target}"
        end
    end
end