---
name: ttt
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^1.0.2"
  go_router: ^8.0.5
  logger: ^1.4.0
  intl: "^0.18.0"
  shared_preferences: "^2.1.2"
  dio: "^5.2.1+1"
  get_it: "^7.6.0"
  flutter_secure_storage: "^8.0.0"
  firebase_core: "^2.14.0"
  firebase_analytics: "^10.4.3"
  firebase_crashlytics: "^3.3.3"
  sentry_flutter: "^7.7.0"
  uuid: "^3.0.7"
  package_info_plus: "^4.0.2"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^2.0.0"
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
  generate: true
